### ISSUE TITLE
Include earlier versions of the rules

### ISSUE THREAD

**Issue by KingSupernova31** [lunakv/academyruins-api#60] opened 2023-07-09 18:28 UTC
Right now the first rulebook in the archives is 5th Edition. Earlier rulebooks were printed booklets, but could be scanned or typed in. There were also ruling compilations released by Wizards, which were effectively updates or addendums to the rulebooks of the time; these could be included too.

**Comment by lunakv** [comment] 2024-02-07 18:42
Closing this as a duplicate of #72

**Closed by lunakv** 2024-02-07 18:42 UTC
Labels: help wanted
